### PR TITLE
💬 Make 3Box Comments more social with Replies, Reactions, and Upvotes

### LINKED ISSUE #20: [900 DAI] Improve 3Box Comments Plugin 💬: Make 3Box Comments more social with Replies, Reactions, and Upvotes
### Prize Bounty 
900 DAI

### Challenge Description

Enhance the 3Box Comments react plugin by adding social features including replies, reaction emojis and upvotes/downvotes. These features will bring improved socailbility, not just to 3Box, but instead to every dapp that uses the plugin. We are looking for a submission that only makes changes to the plugin. There is no need to alter the 3Box Threads API used by the plugin. 

**Guidance:**
It is not possible to alter another persons comment in a thread. To complete this bounty, it will be necessary to create the response (comment, reaction emoji or upvote/downvote) and append it as a new item to the thread. The response should include a reference to the original comment or post. We would only like to allow 2 levels of nested replies - i.e. you can reply to a comment, and reply to a reply. The react component can then filter the thread to display the response in relation to its origin comment.

### Resources

Discord Chat for support: [https://discord.gg/VSG5NnY](https://discord.gg/VSG5NnY)

Documentation: [https://docs.3box.io/build/plugins/comments](https://docs.3box.io/build/plugins/comments)

Demo: [https://3box.github.io/3box-comments-react/examples/dist/](https://3box.github.io/3box-comments-react/examples/dist/)

### Submission Requirements

- Open source code in the form a PR forked from our [Comments Plugin repo](https://github.com/3box/3box-comments-react](https://github.com/3box/3box-comments-react)
- PR should include a description of your solution and the schemas you implemented for the various response types
- A hosted, working demo of the plugin, similar to the demo linked above
- Support for all major web3 enabled browsers
- Share your submission in our Discord in the [Comments channel](https://discord.gg/VSG5NnY)
- Add the label `Gitcoin Global Communities Hackathon` to your PR
- Comments plugin currently works in both Javascript and Typescript projects, this improvement should maintain compatibility 

### Submission Deadline

December 17th 2019

### Judging Criteria

Once the hackathon has finished, we will judge the submission on the following criteria:

**Working Demo:** We will be looking for a working and performant demo. This can be hosted on github pages, netifly or any location that we can access.

**Intuitive User Experience:** We are looking for submissions that most mirror the experience users are familiar with, and the experience that already exists in the component. Delighting the users is also important, but only after functionality is achieved.

**Code Review:** Submissions which meet our requirements in terms of UX, design and performance will be code reviewed by the 3Box team. We are looking for clean, easy to read code.

### Winner Announcement Date

20th December at the latest

### PR DESCRIPTION
**Pull request by think-in-universe**
### Description

Implemented the required enhancements in the GitCoin bounty: https://gitcoin.co/issue/3box/3box-comments-react/20/3760

  - [x] Replies
  - [x] Vote
  - [x] Reactions

**Schemas**:

The schema is defined in the `message` field in each comment in the thread. 
The comment/reply, vote and reaction objects share the same structure, but with different `category`, and `data` type.  
The `parentId` filed is necessary to know which comment the response is sent to. `parentId` will be null if it's a top-level comment

- Comment / Reply
```json
{
  "category": "comment", 
  "data": "some text here", 
  "parentId": "parent_comment_id"
} 
```

- Vote
```json
{
  "category": "vote", 
  "data": -1,  
  "parentId": "parent_comment_id"
} 
```

In the `data` field of a vote object, 1 means upvote and -1 means downvote

- Reaction
```json
{
  "category": "reaction", 
  "data": "emoji symbol here", 
  "parentId": "parent_comment_id"
} 
```

**Manipulations**:

- Comment / Reply
  - reply to comment or reply
  - only comments / replies with depth less than two are allowed to reply
  - all comments / replies are allowed for voting or reacting with emojis
  - delete comments / replies
  - load more comments / replies

- Vote
  - upvote
  - downvote
  - undo vote
  - re-vote
  - vote summary (upvote number - downvote number)

- Reactions
  - react with emoji
  - a bottom bar show statistics of emojis
  - remove my emoji
  - vote for existing emojis in the bar
  - tooltip that shows the users who reacted with the emoji

### Relevant Issues

Fixes: https://github.com/3box/3box-comments-react/issues/20

### Preview

* https://open-tribe.github.io/3box-comments-react/examples/dist/

**Screenshot 1**: Render dialogue that contains replies, reactions and votes:

image

**Screenshot 2**: Reply, vote and react to a comment

image

image

**Screenshot 3**: Show "load more" when a comment contains >5 replies

image

**Screenshot 4**: Show tooltip of the users who has reacted with the emoji

image

### CODE REVIEW

**Comment by think-in-universe** [comment]
Below are some design details worth discussing: 

- [ ] While we limit the depth of replies to two, no such limitation should be added to votes and reactions. ==> In this design, we didn't restrict adding vote or actions to the leaf replies (or replies with depth >= 2)
- [ ] "Load more" should be shown when there're many replies in Dialogue. ==> Here we set the showCommentCount in a reply thread as 5 by default. 
- [ ] Votes count should be shown as "37.1K", or "1.1K" when the number of votes is more than 1K or even 1M. ==> Not implemented yet, but definitely doable. 
- [ ] The current design assumes all the posts are fetched with `thread.getPosts()`, we may need to update the Thread API and data structure if we'd like the component to perform efficiently when there're thousands of comments. 
- [ ] What should be the default sorting order of comments in reply thread and in the main thread? Use reverse chronological order in main thread and then chronological order in reply thread? ==> Here we apply both reverse reverse chronological order for main thread and reply thread
- [ ] Should we disable the deletion of a parent comment in the client if it already has comments, votes or reactions? ==> We didn't disable the deletion of a parent comment now, but plan to do that in an enhancement.
- [ ] The comments count in Context is updated to the count of comments only, by removing votes and reactions here.  ==> Here we only show the number of real comments.

**Comment by think-in-universe** [comment]
Please note this PR here didn't include the bundle.js that is built for the example project. Please let me know in case it's needed to include it in the PR.

**Comment by think-in-universe** [comment]
@RachBLondon @michaelsena @oed could you please anyone help review this PR for the GitCoin issue: https://gitcoin.co/issue/3box/3box-comments-react/20/3760

**Comment by think-in-universe** [comment]
Just F.Y.I., I noticed another developer who contributed to this issue modified his design 18 hours ago (i.e. on Dec 18th) in his PR, after he/she saw my design for this issue (which I submitted on Dec 16th). Some design ideas that I think he learnt (or copied) from my design are: 

1. update the vote button to be the same as my design...
1. show the reply input box by clicking the reply button, which is the same as my design...
1. update the design of the reactions interactions...
1. add the feature for "load more" when replies is more than 5, which is the same as my design...
1. and even the PR description format ....... (I mean the format of PR descriptions, schemas, a d even screenshots, etc.)

image

I don't mean to complain for that guy, but want to point it out these facts, to make the competition fair, since it's an open source competition and everybody can quickly learn from the others' design and even source code easily with minimal cost. I have also reported this issue to GitCoin team, to help us notice these behaviors in an open source competition, and review how to improve the mechanism in the future.

**Comment by RachBLondon** [comment]
@think-in-universe do you have a discord handle I can reach out to you on?

**Pull request merged**
